.\"	$OpenBSD$
.\"
.\" Copyright (c) YYYY YOUR NAME HERE <user@your.dom.ain>
.\" Copyright (c) 2005 Esben Norby <norby@openbsd.org>
.\" Copyright (c) 2004 Claudio Jeker <claudio@openbsd.org>
.\" Copyright (c) 2003, 2004 Henning Brauer <henning@openbsd.org>
.\" Copyright (c) 2002 Daniel Hartmeier <dhartmei@openbsd.org>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate: March 11 2015 $
.Dt NEWD.CONF 5
.Os
.Sh NAME
.Nm newd.conf
.Nd New Daemon configuration file
.Sh DESCRIPTION
The
.Xr newd 8
daemon is a skeleton daemon implementing a privileged separated daemon
in accord with current
.Ox
practices.
.Sh SECTIONS
The
.Nm
config file is divided into three sections.
.Bl -tag -width xxxx
.It Sy Macros
User-defined variables may be defined and used later, simplifying the
configuration file.
.It Sy Global Configuration
Global settings for
.Xr newd 8 .
Global settings can be overruled in groups.
.It Sy Groups
Setting can be grouped together into a number of separate groups that
describe configurations applicable to specific situations.
Attributes specified in groups override global settings.
.El
.Pp
Argument names not beginning with a letter, digit, or underscore
must be quoted.
.Pp
Additional configuration files can be included with the
.Ic include
keyword, for example:
.Bd -literal -offset indent
include "/etc/newd.sub.conf"
.Ed
.Sh MACROS
Macros can be defined that will later be expanded in context.
Macro names must start with a letter, digit, or underscore,
and may contain any of those characters.
Macro names may not be reserved words (for example,
.Ic group )
Macros are not expanded inside quotes.
.Pp
For example:
.Bd -literal -offset indent
hi="5"
group Niven {
	integer-attribute $hi
}
.Ed
.Pp
The same can be accomplished by specifying the integer-attribute
globally or within a group declaration.
.Sh GLOBAL CONFIGURATION
All settings can be configured globally or per group.
.Pp
.Bl -tag -width Ds -compact
.It Xo
.Ic yesno-attribute
.Pq Ic yes Ns | Ns Ic no
.Xc
.Pp
.It Ic integer-attribute Ar integer
.Pp
.It Ic v4address-attribute Ar IPv4address
.Pp
.It Ic v6address-attribute Ar IPv6address
.Pp
.It Ic string-attribute Ar string
.El
.Sh GROUPS
Groups are used for grouping attributes.
All attributes can be configured per group, overruling the global settings.
.Bl -tag -width group-name
.It Ic group Ar name
Specify a group, grouping one or more attributes.
.El
.Pp
For example:
.Bd -literal -offset indent
yesno-attribute no;
group Barrymore {
	yesno-attribute yes;
	integer-attribute 231;
	string-attribute "Sparks";
	v4address-attribute 1.2.3.4;
	v6address-attribute ::1;
}
.Ed
.Sh FILES
.Bl -tag -width "/etc/newd.conf" -compact
.It Pa /etc/newd.conf
.Xr newd 8
configuration file
.El
.Sh SEE ALSO
.Xr newd 8 ,
.Xr newdfctl 8 ,
.Xr rc.conf.local 8
.Sh HISTORY
The
.Nm
file format first appeared in
.Ox X.Y .
